/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/players/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Get player profile summary.
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *
         *     Returns:
         *         PlayerSummary with profile info and current deck
         */
        get: operations["get_player_players__tag__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{tag}/battlelog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Battlelog
         * @description Get player's recent battle history.
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *         limit: Number of recent battles (default 20, max 100)
         *
         *     Returns:
         *         List of recent battles
         */
        get: operations["get_player_battlelog_players__tag__battlelog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{tag}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Deck
         * @description Get player's current deck with per-card elixir info and avg elixir.
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *
         *     Returns:
         *         Current deck with per-card stats and average elixir cost
         */
        get: operations["get_player_deck_players__tag__deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{tag}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Stats
         * @description Get player's recent battle statistics (win rate, avg elixir used).
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *         limit: Number of recent battles to consider (default 20, max 100)
         *
         *     Returns:
         *         BattleStats summarizing the player's recent battlelog
         */
        get: operations["get_player_stats_players__tag__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{tag}/advice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Advice
         * @description Get complete gameplay advice for a player.
         *
         *     Combines:
         *     - Player profile & recent battles
         *     - Deck analysis (archetype, flags, win rate)
         *     - Rule-based swap suggestions & general tips
         *     - Optional LLM-powered summary
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *         include_llm: Include optional LLM summary if API key is configured (default True)
         *
         *     Returns:
         *         Advice object with analysis, suggestions, and optional LLM summary
         */
        get: operations["get_player_advice_players__tag__advice_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{tag}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Witch
         * @description Ask a single, free-text question about a player's current deck.
         *
         *     Stateless: each call is answered independently with no memory of
         *     previous questions for this (or any) tag - nothing is persisted here.
         *
         *     Args:
         *         tag: Player tag (with or without #)
         *         request: The question to ask
         *
         *     Returns:
         *         AskResponse with the witch's answer
         *
         *     Raises:
         *         HTTPException 400: if OPENROUTER_API_KEY isn't configured, the
         *             player/deck can't be fetched, or every configured model failed
         *             to produce an answer
         */
        post: operations["ask_witch_players__tag__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Cards
         * @description Get all available Clash Royale cards with details.
         *
         *     Triggers a catalog refresh (cached, see RoyaleClient.get_cards) and
         *     returns the deduplicated, persisted card list.
         *
         *     Returns:
         *         Typed list of cards with elixir cost, rarity, and type.
         */
        get: operations["get_all_cards_cards__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Card By Id
         * @description Get a single card by its Royale API card id.
         *
         *     Args:
         *         card_id: The card's numeric id
         *
         *     Returns:
         *         Card details (elixir, rarity, type)
         */
        get: operations["get_card_by_id_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Simple health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Advice
         * @description Complete gameplay advice for a player.
         */
        Advice: {
            /** Tag */
            tag: string;
            /** Name */
            name: string;
            /** Trophies */
            trophies: number;
            /** Current Deck */
            current_deck: string[];
            analysis: components["schemas"]["DeckAnalysis"];
            /** Suggested Swaps */
            suggested_swaps: components["schemas"]["TipDetail"][];
            /** General Tips */
            general_tips: components["schemas"]["TipDetail"][];
            /** Llm Summary */
            llm_summary?: string | null;
        };
        /**
         * AskRequest
         * @description A single, stateless free-text question for the /ask endpoint.
         */
        AskRequest: {
            /** Question */
            question: string;
        };
        /**
         * AskResponse
         * @description The witch's single answer - no conversation history is kept.
         */
        AskResponse: {
            /** Answer */
            answer: string;
        };
        /**
         * BattleStats
         * @description Player's recent battle statistics.
         */
        BattleStats: {
            /** Total Battles */
            total_battles: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** Win Rate */
            win_rate: number;
            /** Avg Elixir Last Battles */
            avg_elixir_last_battles: number;
        };
        /**
         * Card
         * @description Clash Royale card.
         */
        Card: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Elixir */
            elixir: number;
            /** Rarity */
            rarity: string;
            /** Type */
            type: string;
            /** Icon Url */
            icon_url?: string | null;
        };
        /**
         * CardCatalogResponse
         * @description Typed response for GET /cards/.
         */
        CardCatalogResponse: {
            /** Total */
            total: number;
            /** Cards */
            cards: components["schemas"]["Card"][];
        };
        /**
         * DeckAnalysis
         * @description Analyzed deck with classification and flags.
         */
        DeckAnalysis: {
            /** Archetype */
            archetype: string;
            /** Avg Elixir */
            avg_elixir: number;
            /** Card Count */
            card_count: number;
            /** Flagged Issues */
            flagged_issues: components["schemas"]["IssueDetail"][];
            /** Strengths */
            strengths: components["schemas"]["StrengthDetail"][];
            /** Win Rate */
            win_rate: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IssueDetail
         * @description A single flagged deck issue: a structured code plus its rendered message.
         */
        IssueDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * PlayerDeckView
         * @description Typed response for GET /players/{tag}/deck.
         */
        PlayerDeckView: {
            /** Tag */
            tag: string;
            /** Name */
            name: string;
            /** Cards */
            cards: components["schemas"]["Card"][];
            /** Avg Elixir */
            avg_elixir: number;
            /** Card Count */
            card_count: number;
        };
        /**
         * PlayerSummary
         * @description Player profile summary.
         */
        PlayerSummary: {
            /** Tag */
            tag: string;
            /** Name */
            name: string;
            /** Trophies */
            trophies: number;
            /** Best Trophies */
            best_trophies: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Draws */
            draws: number;
            /** King Level */
            king_level?: number | null;
            /** Current Deck */
            current_deck: components["schemas"]["Card"][];
        };
        /**
         * StrengthDetail
         * @description A single deck strength: a structured code plus its rendered message.
         */
        StrengthDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * TipDetail
         * @description A single piece of advice, tagged by where it came from.
         */
        TipDetail: {
            /** Text */
            text: string;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_player_players__tag__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_battlelog_players__tag__battlelog_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_deck_players__tag__deck_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDeckView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_stats_players__tag__stats_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BattleStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_advice_players__tag__advice_get: {
        parameters: {
            query?: {
                include_llm?: boolean;
            };
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Advice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_witch_players__tag__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_cards_cards__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardCatalogResponse"];
                };
            };
        };
    };
    get_card_by_id_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
